apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: latency
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app: zeaz-api
  delay:
    latency: "200ms"
    correlation: "50"
