server {
  trust_domain = "zypto.global"
  data_dir = "/run/spire/data"
  log_level = "INFO"
  bind_address = "0.0.0.0"
  bind_port = "8081"
}

plugins {
  DataStore "sql" {
    plugin_data {
      database_type = "sqlite3"
      connection_string = "/run/spire/data/datastore.sqlite3"
    }
  }

  NodeAttestor "k8s_psat" {
    plugin_data {
      clusters = {
        "primary" = {
          service_account_allow_list = ["spire-system:spire-agent"]
        }
      }
    }
  }

  KeyManager "disk" {
    plugin_data {
      keys_path = "/run/spire/data/keys.json"
    }
  }

  UpstreamAuthority "disk" {
    plugin_data {
      cert_file_path = "/run/spire/config/ca.crt"
      key_file_path = "/run/spire/config/ca.key"
    }
  }
}

federation {
  bundle_endpoint {
    address = "0.0.0.0"
    port = 8443
    profile "https_web" {
      endpoint_path = "/spire/bundle"
    }
  }
}
