apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zeaz-secret
  namespace: zeaz
spec:
  encryptedData:
    password: AgBy...
  template:
    metadata:
      name: zeaz-secret
      namespace: zeaz
    type: Opaque
