apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zeaz
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zeaz
subjects:
  - kind: ServiceAccount
    name: zeaz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zeaz
