apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mm2
  namespace: trading
spec:
  version: 3.7.0
  replicas: 2
  clusters:
    - alias: a
      bootstrapServers: kafka-a-kafka-bootstrap.trading.svc:9092
    - alias: b
      bootstrapServers: kafka-b-kafka-bootstrap.trading.svc:9092
  mirrors:
    - sourceCluster: a
      targetCluster: b
      sourceConnector:
        tasksMax: 4
      heartbeatConnector:
        tasksMax: 2
      checkpointConnector:
        tasksMax: 2
      topicsPattern: ".*"
      groupsPattern: ".*"
    - sourceCluster: b
      targetCluster: a
      sourceConnector:
        tasksMax: 4
      heartbeatConnector:
        tasksMax: 2
      checkpointConnector:
        tasksMax: 2
      topicsPattern: ".*"
      groupsPattern: ".*"
