apiVersion: apps/v1
kind: Deployment
metadata:
  name: zcyptobot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zcyptobot
  template:
    metadata:
      labels:
        app: zcyptobot
    spec:
      containers:
        - name: zcyptobot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
